CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921144440_Initial') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        username character varying(50) NOT NULL,
        password_hashed text NOT NULL,
        email character varying(255) NOT NULL,
        first_name character varying(50) NOT NULL,
        last_name character varying(50) NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921144440_Initial') THEN
    CREATE UNIQUE INDEX ix_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921144440_Initial') THEN
    CREATE UNIQUE INDEX ix_users_username ON users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921144440_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260921144440_Initial', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921220848_AddWorkout') THEN
    CREATE TABLE workouts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        exercise_type character varying(20) NOT NULL,
        duration_minutes integer NOT NULL,
        calories_burned integer NOT NULL,
        intensity integer NOT NULL,
        fatigue integer NOT NULL,
        notes character varying(1000),
        performed_at timestamp with time zone NOT NULL,
        user_id integer NOT NULL,
        CONSTRAINT pk_workouts PRIMARY KEY (id),
        CONSTRAINT "CK_Workouts_Calories" CHECK (calories_burned >= 0),
        CONSTRAINT "CK_Workouts_Duration" CHECK (duration_minutes > 0),
        CONSTRAINT "CK_Workouts_Fatigue" CHECK (fatigue BETWEEN 1 AND 10),
        CONSTRAINT "CK_Workouts_Intensity" CHECK (intensity BETWEEN 1 AND 10),
        CONSTRAINT fk_workouts_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921220848_AddWorkout') THEN
    CREATE INDEX ix_workouts_user_id_performed_at ON workouts (user_id, performed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921220848_AddWorkout') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260921220848_AddWorkout', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260924161554_AddIsGoogleAccountToUser') THEN
    ALTER TABLE users ADD is_google_account boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260924161554_AddIsGoogleAccountToUser') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260924161554_AddIsGoogleAccountToUser', '10.0.3');
    END IF;
END $EF$;
COMMIT;

